Adding infrastructure destruction

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -71,9 +71,9 @@ jobs:
         run: terraform plan 
         continue-on-error: false
 
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+      #- name: Terraform Plan Status
+      #  if: steps.plan.outcome == 'failure'
+      #  run: exit 1
 
 
       - name: Terraform Apply
